# -*- coding: utf-8 -*-
"""Customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZaWWezTP4flsgm55EObIByST5E3zBsDj
"""
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

from transformers import DistilBertTokenizer
from transformers import DistilBertForSequenceClassification
from transformers import Trainer, TrainingArguments

from datasets import Dataset

import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("telco_churn_transformer_dataset.csv")

df.head()

train_text, temp_text, train_labels, temp_labels = train_test_split(
    df["text"], df["label"], test_size=0.30, random_state=42
)

dev_text, test_text, dev_labels, test_labels = train_test_split(
    temp_text, temp_labels, test_size=0.33, random_state=42
)

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

train_enc = tokenizer(list(train_text), truncation=True, padding=True, max_length=128)
dev_enc = tokenizer(list(dev_text), truncation=True, padding=True, max_length=128)
test_enc = tokenizer(list(test_text), truncation=True, padding=True, max_length=128)

train_dataset = Dataset.from_dict({
    "input_ids": train_enc["input_ids"],
    "attention_mask": train_enc["attention_mask"],
    "labels": list(train_labels)
})

dev_dataset = Dataset.from_dict({
    "input_ids": dev_enc["input_ids"],
    "attention_mask": dev_enc["attention_mask"],
    "labels": list(dev_labels)
})

test_dataset = Dataset.from_dict({
    "input_ids": test_enc["input_ids"],
    "attention_mask": test_enc["attention_mask"],
    "labels": list(test_labels)
})

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs"
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average="binary"
    )

    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics
)
trainer.train()
trainer.save_model("model")
tokenizer.save_pretrained("model")

results = trainer.predict(test_dataset)

print("Evaluation Metrics:")
print(results.metrics)

preds = np.argmax(results.predictions, axis=1)

cm = confusion_matrix(results.label_ids, preds)

print(cm)

plt.figure(figsize=(6,4))

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["No Churn","Churn"],
            yticklabels=["No Churn","Churn"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

text = """
The customer has month to month contract.
Internet service is fiber optic.
Monthly charges are 90 dollars.
Payment method is electronic check.
"""

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)

prediction = torch.argmax(outputs.logits).item()

print("Churn Prediction:", "Yes" if prediction==1 else "No")